name: Create release for genanki.js

on:
  workflow_dispatch:  
  
env:
  version: 'v2.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        sudo apt install zip wget -q -y     

        # bundle all files in genanki folder to dist, demo and sample folder
        sudo npm install gulp gulp-concat
        npm link gulp
        gulp bundleJs

        # remove node_modules and package.json generated when using gulp
        rm -rf node_modules
        rm -rf package-lock.json

        # commit changes
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        
        if [ -n "$(git status --porcelain)" ]; then
          echo "there are changes";
          git commit -am "${{ env.version }}"
          git push
        else
          echo "no changes";
        fi
        
        
        # Create folder for release
        mkdir genanki-${{ env.version }}
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: genanki-${{ env.version }}
        bodyFile: 'release.md'
        tag: ${{ env.version }}
        artifacts: genanki-${{ env.version }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}